# game_all
 /usr/bin/curl -H "Host: itunes.apple.com" -H "User-Agent: iTunes-iPod/5.1.1 (4; 8GB; dt:71)" -H "Accept: */*" -H "Accept-Language: zh-Hans;q=1.0,en;q=1.0,fr;q=0.9,de;q=0.9,ja;q=0.9,nl;q=0.9,it;q=0.8,es;q=0.8,pt;q=0.8,pt-PT;q=0.7,da;q=0.7,fi;q=0.7,nb;q=0.7,sv;q=0.6,ko;q=0.6,zh-Hant;q=0.6,ru;q=0.5,pl;q=0.5,tr;q=0.5,uk;q=0.5,ar;q=0.4,hr;q=0.4,cs;q=0.4,el;q=0.3,he;q=0.3,ro;q=0.3,sk;q=0.3,th;q=0.2,id;q=0.2,ms;q=0.2,en-GB;q=0.1,ca;q=0.1,hu;q=0.1,vi;q=0.1" -H "X-Apple-Partner: origin.0" -H "X-Apple-Connection-Type: WiFi" -H "X-Apple-Client-Application: Software" -H "X-Apple-Client-Versions: GameCenter/2.0" -H "X-Dsid: 400453337" -H "X-Apple-Store-Front: 143465-19,4" -H "Accept-Encoding: gzip, deflate" -H "Connection: keep-alive" -H "Connection: keep-alive" "http://itunes.apple.com/WebObjects/MZStore.woa/wa/viewAutoSourcedGenrePage?id=6014&showTopLevelGenre=true&selected-tab-index=1&top-ten-m=42" | /bin/gzip -d | /bin/grep \<key\>title\<\/key\> | /bin/awk -F'<string>' '{print $2}' | /bin/sed -e 's:\<\/string\>::g' > /root/rank/cn_game_all_`date +%Y%m%dT%H%M`.txt

# game_strategy
# /usr/bin/curl -H "Host: itunes.apple.com" -H "User-Agent: iTunes-iPod/5.1.1 (4; 8GB; dt:71)" -H "Accept: */*" -H "Accept-Language: zh-Hans;q=1.0,en;q=1.0,fr;q=0.9,de;q=0.9,ja;q=0.9,nl;q=0.9,it;q=0.8,es;q=0.8,pt;q=0.8,pt-PT;q=0.7,da;q=0.7,fi;q=0.7,nb;q=0.7,sv;q=0.6,ko;q=0.6,zh-Hant;q=0.6,ru;q=0.5,pl;q=0.5,tr;q=0.5,uk;q=0.5,ar;q=0.4,hr;q=0.4,cs;q=0.4,el;q=0.3,he;q=0.3,ro;q=0.3,sk;q=0.3,th;q=0.2,id;q=0.2,ms;q=0.2,en-GB;q=0.1,ca;q=0.1,hu;q=0.1,vi;q=0.1" -H "X-Apple-Partner: origin.0" -H "X-Apple-Connection-Type: WiFi" -H "X-Apple-Client-Application: Software" -H "X-Apple-Client-Versions: GameCenter/2.0" -H "X-Dsid: 400453337" -H "X-Apple-Store-Front: 143465-19,4" -H "Accept-Encoding: gzip, deflate" -H "Connection: keep-alive" -H "Connection: keep-alive" "http://itunes.apple.com/WebObjects/MZStore.woa/wa/viewAutoSourcedGenrePage?id=7017&selected-tab-index=1&top-ten-m=42" | /bin/gzip -d | /bin/grep \<key\>title\<\/key\> | /bin/awk -F'<string>' '{print $2}' | /bin/sed -e 's:\<\/string\>::g' > /root/rank/cn_game_strategy_`date +%Y%m%dT%H%M`.txt

# game_puzzle
# /usr/bin/curl -H "Host: itunes.apple.com" -H "User-Agent: iTunes-iPod/5.1.1 (4; 8GB; dt:71)" -H "Accept: */*" -H "Accept-Language: zh-Hans;q=1.0,en;q=1.0,fr;q=0.9,de;q=0.9,ja;q=0.9,nl;q=0.9,it;q=0.8,es;q=0.8,pt;q=0.8,pt-PT;q=0.7,da;q=0.7,fi;q=0.7,nb;q=0.7,sv;q=0.6,ko;q=0.6,zh-Hant;q=0.6,ru;q=0.5,pl;q=0.5,tr;q=0.5,uk;q=0.5,ar;q=0.4,hr;q=0.4,cs;q=0.4,el;q=0.3,he;q=0.3,ro;q=0.3,sk;q=0.3,th;q=0.2,id;q=0.2,ms;q=0.2,en-GB;q=0.1,ca;q=0.1,hu;q=0.1,vi;q=0.1" -H "X-Apple-Partner: origin.0" -H "X-Apple-Connection-Type: WiFi" -H "X-Apple-Client-Application: Software" -H "X-Apple-Client-Versions: GameCenter/2.0" -H "X-Dsid: 400453337" -H "X-Apple-Store-Front: 143465-19,4" -H "Accept-Encoding: gzip, deflate" -H "Connection: keep-alive" -H "Connection: keep-alive" "http://itunes.apple.com/WebObjects/MZStore.woa/wa/viewAutoSourcedGenrePage?id=7012&selected-tab-index=1&top-ten-m=42" | /bin/gzip -d | /bin/grep \<key\>title\<\/key\> | /bin/awk -F'<string>' '{print $2}' | /bin/sed -e 's:\<\/string\>::g' > /root/rank/cn_game_puzzle_`date +%Y%m%dT%H%M`.txt


# all
# /usr/bin/curl -H "Host: itunes.apple.com" -H "User-Agent: iTunes-iPod/5.1.1 (4; 8GB; dt:71)" -H "Accept: */*" -H "Accept-Language: zh-Hans;q=1.0,en;q=1.0,fr;q=0.9,de;q=0.9,ja;q=0.9,nl;q=0.9,it;q=0.8,es;q=0.8,pt;q=0.8,pt-PT;q=0.7,da;q=0.7,fi;q=0.7,nb;q=0.7,sv;q=0.6,ko;q=0.6,zh-Hant;q=0.6,ru;q=0.5,pl;q=0.5,tr;q=0.5,uk;q=0.5,ar;q=0.4,hr;q=0.4,cs;q=0.4,el;q=0.3,he;q=0.3,ro;q=0.3,sk;q=0.3,th;q=0.2,id;q=0.2,ms;q=0.2,en-GB;q=0.1,ca;q=0.1,hu;q=0.1,vi;q=0.1" -H "X-Apple-Partner: origin.0" -H "X-Apple-Connection-Type: WiFi" -H "X-Apple-Client-Application: Software" -H "X-Apple-Client-Versions: GameCenter/2.0" -H "X-Dsid: 400453337" -H "X-Apple-Store-Front: 143465-19,4" -H "Accept-Encoding: gzip, deflate" -H "Connection: keep-alive" -H "Connection: keep-alive" "http://itunes.apple.com/WebObjects/MZStore.woa/wa/viewTop?selected-tab-index=1&top-ten-m=42&genreId=36" | /bin/gzip -d | /bin/grep \<key\>title\<\/key\> | /bin/awk -F'<string>' '{print $2}' | /bin/sed -e 's:\<\/string\>::g' > /root/rank/cn_all_`date +%Y%m%dT%H%M`.txt

# wheather 
/usr/bin/curl -H "Host: itunes.apple.com" -H "User-Agent: iTunes-iPod/5.1.1 (4; 8GB; dt:71)" -H "Accept: */*" -H "Accept-Language: zh-Hans;q=1.0,en;q=1.0,fr;q=0.9,de;q=0.9,ja;q=0.9,nl;q=0.9,it;q=0.8,es;q=0.8,pt;q=0.8,pt-PT;q=0.7,da;q=0.7,fi;q=0.7,nb;q=0.7,sv;q=0.6,ko;q=0.6,zh-Hant;q=0.6,ru;q=0.5,pl;q=0.5,tr;q=0.5,uk;q=0.5,ar;q=0.4,hr;q=0.4,cs;q=0.4,el;q=0.3,he;q=0.3,ro;q=0.3,sk;q=0.3,th;q=0.2,id;q=0.2,ms;q=0.2,en-GB;q=0.1,ca;q=0.1,hu;q=0.1,vi;q=0.1" -H "X-Apple-Partner: origin.0" -H "X-Apple-Connection-Type: WiFi" -H "X-Apple-Client-Application: Software" -H "X-Apple-Client-Versions: GameCenter/2.0" -H "X-Dsid: 400453337" -H "X-Apple-Store-Front: 143465-19,4" -H "Accept-Encoding: gzip, deflate" -H "Connection: keep-alive" -H "Connection: keep-alive" "http://itunes.apple.com/WebObjects/MZStore.woa/wa/viewAutoSourcedGenrePage?id=6001&selected-tab-index=1&top-ten-m=42" | /bin/gzip -d | /bin/grep \<key\>title\<\/key\> | /bin/awk -F'<string>' '{print $2}' | /bin/sed -e 's:\<\/string\>::g' > /root/rank/cn_wheather_`date +%Y%m%dT%H%M`.txt
