#! /bin/sh
# 
# usage:
#     sudo chmod +rx view_rank    
#     view_rank country rank_name app_name last_change_amount
# 
# view the recent rank change by country by app_rank by app_name

# file_path (ended with /)
file_path=./rank/

country=$1

usage()
{
    echo "Usage : "
    echo "    chmod +rx $0"
    echo "    $0 country [rank_name [app_name [last_change_amount]]]"
    echo "  Example:"
    echo "    $0 cn grossing 霸气三国 5"
}

if [ $# -eq 4 ]; then
    echo "==== iPhone ===="
    echo "  $3 @ $2 : ";
    grep -H -e "$3" "$file_path""$country"_$2*.txt | sed -e "s:^:    :" -e "s:</string>::" -e "s:\.txt\:: :" -e "s:$4$5\_::" -e "s:T: :" -e "s:\(\ [0-9][0-9]\)\([0-9][0-9]\ \):\1\:\2:" -e "s:\(\ [0-9][0-9][0-9][0-9]\)\([0-9][0-9]\)\([0-9][0-9]\ \):\1\-\2\-\3:" | tail -n $4;
    echo "";
    echo "==== iPad ===="
    echo "  $3 @ $2 : ";
    grep -H -e "$3" "$file_path""$country"_pad_$2*.txt | sed -e "s:^:    :" -e "s:</string>::" -e "s:\.txt\:: :" -e "s:$4$5\_::" -e "s:T: :" -e "s:\(\ [0-9][0-9]\)\([0-9][0-9]\ \):\1\:\2:" -e "s:\(\ [0-9][0-9][0-9][0-9]\)\([0-9][0-9]\)\([0-9][0-9]\ \):\1\-\2\-\3:" | tail -n $4;
    echo "";
else
    if [ $# -eq 3 ]; then
        echo "==== iPhone ===="
        cat `ls -t "$file_path""$country"_"$2"_*.txt | head -n 1` | grep $3
        echo "";
        echo "==== iPad ===="
        cat `ls -t "$file_path""$country"_pad_"$2"_*.txt | head -n 1` | grep $3
        echo "";
    else
        if [ $# -eq 2 ]; then
            echo "==== iPhone ===="
            cat `ls -t "$file_path""$country"_"$2"_*.txt | head -n 1` | head -n 54
            echo "";
            echo "==== iPad ===="
            cat `ls -t "$file_path""$country"_pad_"$2"_*.txt | head -n 1` | head -n 50
            echo "";
        else
            usage
        fi
    fi
fi
